### PR TITLE
feat: Implement topbar outside of the main page

### PR DESCRIPTION
**Pull request by georgi4444**

### CODE REVIEW

**Comment by Tschonti** [comment]
lgtm, one weird thing: the topbar disappears when you scroll almost to the bottom, tho this might be a nextUI thing

**Comment by georgi4444** [comment]
> lgtm, one weird thing: the topbar disappears when you scroll almost to the bottom, tho this might be a nextUI thing

I think it is nextui, I couldnt figure it out

**Comment by georgi4444** [comment]
> lgtm, one weird thing: the topbar disappears when you scroll almost to the bottom, tho this might be a nextUI thing

fixed in https://github.com/jst-seminar-rostlab-tum/wfp-hunger-map/pull/28/commits/ca901170d2c314b4c0344639091f81846631e65c

**Review by marinovl7 — APPROVED** [review]
It's a pleasure to finally see the first perfect PR, without any code style issues, done perfectly!

**Pull request merged**
